server:
  port: 8080

spring:
  application:
    name: sla-service

  datasource:
    url: jdbc:postgresql://db:5432/sla
    username: sla_user
    password: sla_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: never

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

springdoc:
  swagger-ui:
    path: /docs

sla:
  b2c:
    reaction-minutes: 30
    to-assembly-hours: 4
    assembly-to-delivery-days: 1
    total-days: 2